services:
  frontend-eduardovedes:
    container_name: eduardovedes-frontend
    image: ghcr.io/evedes/eduardovedes/frontend:latest
    restart: unless-stopped
    networks:
      - batmanvps
networks:
  batmanvps:
    external: true
